[mcp_servers.astro]
url = "https://mcp.docs.astro.build/mcp"

[mcp_servers.shadcn]
command = "npx"
args = [
    "shadcn",
    "mcp",
]

[mcp_servers.xcode-tools]
command = "xcrun"
args = [
    "mcpbridge",
]
